version: '3.8'

services: 
  jenkins:
    container_name: Jenkins
    build: 
      context: ./
      labels: 
        com.lojasoft.descripcion: "Jenkins CI"
        com.lojasoft.titulo: "Jenkins"          
    environment:
      - JENKINS_ENV=${JENKINGS_ENV}
    stdin_open: true
    tty: true
    volumes:
      - ./Jenkings:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - '8080:8080'
      - '50000:50000' 
    privileged: false
    user: root
    restart: on-failure

volumes: 
  lojasoft-jenkins: